### PR TITLE
Get ratos version directly from system

### PR DESCRIPTION
**Pull request by GP3D84**

### CODE REVIEW

**Comment by HelgeKeck** [comment]
hey, thanks for the contribution. next time please add some spaces.

instead this here:
`RatOS '+ ratos_version() +'</p>`

please do this
`RatOS ' + ratos_version() + '</p>`

**Comment by GP3D84** [comment]
> hey, thanks for the contribution. next time please add some spaces.

Hi, Done :)

**Comment by HelgeKeck** [comment]
also, please add a fallback and a default value to the function in case the file cant be read. best is to try and catch it. and please check if the split works before sending it

```
def ratos_version():
	"""
	Get current version of RatOS distro.
	"""
	with open("/etc/ratos-release") as f:
		return f.read().split()[1]
```

**Comment by HelgeKeck** [comment]
and please put the function under the helper category
image

**Comment by GP3D84** [comment]
When I tried to put it into the class, version not load correctly
 Honestly, I haven't investigated much, I'll try again when I'm at home

**Comment by HelgeKeck** [comment]
> When I tried to put it into the class, version not load correctly Honestly, I haven't investigated much, I'll try again when I'm at home

this is how it works

```
def get_ratos_version(self):
	"""
	Get current version of RatOS distro.
	"""
	try:
		with open("/etc/ratos-release") as f:
			return f.read().split()[1]
	except Exception as exc:
		self.debug_echo("get_ratos_version", "Something went wrong. " + str(exc))
	return "v2.1"

```

**Comment by HelgeKeck** [comment]
you call it then like this
`RatOS ' + self.get_ratos_version() + '</p>`

**Comment by HelgeKeck** [comment]
put it here
image

**Comment by GP3D84** [comment]
@HelgeKeck done and thank you for your help

**Comment by HelgeKeck** [comment]
now please fix the double empty line and you are done
image
only one emtpy line

**Comment by HelgeKeck** [comment]
after that im ok with it

**Review by HelgeKeck — APPROVED** [review]

**Comment by GP3D84** [comment]
Maybe it would be useful to save as register_command  for use elsewhere?
eg. https://github.com/GP3D84/RatOS-configuration/blob/development/macros/calibration.cfg#L65

**Comment by HelgeKeck** [comment]
> Maybe it would be useful to save as register_command for use elsewhere? eg. https://github.com/GP3D84/RatOS-configuration/blob/development/macros/calibration.cfg#L65

i think i will jsut remoce the version tags from such messages, no need to worry now

**Comment by miklschmidt** [comment]
Thank you!

**Pull request merged**
