### PR TITLE
Separate homing (physical - sensorless)

### PR DESCRIPTION
**Pull request by mcr83**
This pull is to separate X and Y axis in homing management in order to have a mixed configuration.
In my case, it is to have X with physical endstops and Y with sensorless homing on TMC2209.
In basically create two different physical-endstops.cfg (one X, one Y), two different tmc2209-sensorless.cfg (one X, one Y) and modify [homing_override] in order to use different variables.

### CODE REVIEW

**Comment by miklschmidt** [comment]
I only have one request for this: Add physical-endstops.cfg back and make it include physical-endstops-x and physical-endstops-y, that way we ensure backwards compatibility. Same for the sensorless homing template.

**Comment by mcr83** [comment]
Retrocompatibility was not in my mind. Now I've added all files back and they can be used for endstops setup on both X and Y.
There is also another set of IFs if only old homing variable is defined.

**Comment by miklschmidt** [comment]
Beautiful, will test ASAP and get this merged :)

**Comment by mcr83** [comment]
Another consideration: In my printer, Y homing is to Y Max (using Y Endstop holder as a bumper).
Now with Enclosure 2.0 Ratrig released printable Y Min bumper. I don't know if it is possible to set homing direction with a macro, but maybe default option should be to home Y to Y Min. What do you think about it?

**Comment by miklschmidt** [comment]
It already was https://github.com/Rat-OS/RatOS-configuration/blob/development/templates/sensorless-homing-tmc2209.cfg

but i see you are missing a bunch of that in the new templates.

**Comment by miklschmidt** [comment]
I've redone this in v2.0

**Pull request closed without merging**
