### PR TITLE
Add Octopus Max EZ

### PR DESCRIPTION
**Pull request by FlorianKoegler**
Hi, 

I'd like to propose this merge request to add the BTT Octopus Max EZ board. 
I have been using this configuration for a while in my V-Core 3.1. 

### Open TODOS:
- The board's image in wiring.drawio.svg should be hosted somewhere else (RatOS website?).

- ADXL345 section is left out from config.cfg.

I see that most boards use the hardware SPI interface there, which would be:
```
[adxl345]
spi_bus: spi4
cs_pin: adxl345_cs_pin
```

However for use with TMC5160s it is necessary to switch to software SPI, i.e.:
```
[adxl345]
spi_software_sclk_pin: stepper_spi_sclk_pin
spi_software_mosi_pin: stepper_spi_mosi_pin
spi_software_miso_pin: stepper_spi_miso_pin
cs_pin: adxl345_cs_pin
```
To my knowledge, it is not possible to "undefine" the `spi_bus: spi4`, if it would be included in config.cfg. 
Which means that the whole file would need to be replaced by users?
Maybe I am missing something. 😅

### CODE REVIEW

**Review by LongLiveCHIEF — COMMENTED** [review]
I noticed this has the 2pin fans in your wiring diagram.  This board appears to have native support for 4pin 12 volt fans.  I wonder if this should be reflected in the wiring diagram since that's become the de-facto store option for the Vcore kit?

**Comment by LongLiveCHIEF** [comment]
@FlorianKoegler let me know if there's anything you'd like me to test.  I have this board and various screens, probes, fans, and toolboards, filament runout, etc...

**Comment by FlorianKoegler** [comment]
> I noticed this has the 2pin fans in your wiring diagram. This board appears to have native support for 4pin 12 volt fans. I wonder if this should be reflected in the wiring diagram since that's become the de-facto store option for the Vcore kit?

Hi Brian, 
You're right, the board natively supports PWM fans (24V is also fine) with the same pinout as PC fans. :)
I decided to keep the 2 Pin Fans to show the same components as the other boards. 
I don't think we can show any useful wiring information here, because the colors are not standardized, so you have to refer to the fans datasheet. 

But it would make sense to add some explanation on the RatOS documentation website. Maybe a small picture showing the pinout of one fan (with the pin names), showing the orientation, should be fine?

**Comment by FlorianKoegler** [comment]
> @FlorianKoegler let me know if there's anything you'd like me to test. I have this board and various screens, probes, fans, and toolboards, filament runout, etc...

Thanks for the offer! So far, I have used the following things:
- 2 Pin Fans, 4 Pin Fans
- NTC, PT1000 thermistors (as e.g. in the Phaetus Rapido, using the pullup jumper)
- TMC2209s (UART, with 24V), TMC5160s (Software SPI, with 48V)
- SuperPinda
- Endstops from the RatRig Kit

I'm running the board in my printer for several months, so the core functionality should be verified, imho.
Screens, other probes and runout sensors are not tested from my side, although I'm not sure about the necessity. 

Me and another Discord user had issues getting ADXL to work, while also using a TMC5160 (or other SPI based stepper drivers).
Either the ADXL or TMC5160 were non-responsive. 
It could be due to some user error or a weird ADXL module I had.
So this might be something you could look into. 😅

**Comment by miklschmidt** [comment]
This looks good!

For the ADXL345, add:
```
[adxl345]
spi_software_sclk_pin: stepper_spi_sclk_pin
spi_software_mosi_pin: stepper_spi_mosi_pin
spi_software_miso_pin: stepper_spi_miso_pin
cs_pin: adxl345_cs_pin
```

This should work regardless of driver communication protocol.

I'll take care of moving the wiring diagram to the docs :+1:

**Comment by FlorianKoegler** [comment]
> This looks good!
> 
> For the ADXL345, add:
> 
> ```
> [adxl345]
> spi_software_sclk_pin: stepper_spi_sclk_pin
> spi_software_mosi_pin: stepper_spi_mosi_pin
> spi_software_miso_pin: stepper_spi_miso_pin
> cs_pin: adxl345_cs_pin
> ```
> 
> This should work regardless of driver communication protocol.
> 
> I'll take care of moving the wiring diagram to the docs 👍

Thanks! I have added the ADXL345 section.

**Comment by miklschmidt** [comment]
Excellent, with regards to the 4-pin fans, RatOS uses a separate fan wiring diagram, see: [https://os.ratrig.com/assets/files/manta-m8p-fan-wiring-e34a6a9014acaf2bb0367699691518b5.svg](https://os.ratrig.com/assets/files/manta-m8p-fan-wiring-e34a6a9014acaf2bb0367699691518b5.svg)

Source is here https://github.com/Rat-OS/RatOS-configuration/blob/v2.x/boards/btt-manta-m8p/fan-wiring.drawio.svg

**Comment by LongLiveCHIEF** [comment]
woooot!

**Pull request merged**
