### PR TITLE
Macros: make driver type a variable

### PR DESCRIPTION
**Pull request by miklschmidt**
This fixes prusa mk3s sensorless homing issues.

### CODE REVIEW

**Comment by smwoodward** [comment]
Might not be a bad idea to add this for the vorons also.

**Comment by miklschmidt** [comment]
@smwoodward it's 2209 by default (see: https://github.com/Rat-OS/RatOS-configuration/pull/136/files#diff-ba7a6f7869efc9d4042a8e1ce3124f9c9c676597b2bd342a19a591bec5177c8bR53), which is the most common. Not sure what you want me to add to the voron configs?

These two variables will soon be documented here: https://os.ratrig.com/docs/configuration/macros#homing

**Comment by smwoodward** [comment]
2209 isn't the only drivers people are using.

**Comment by miklschmidt** [comment]
@smwoodward no that's why they can change it now.

**Comment by smwoodward** [comment]
Ahh ok. I thought I saw it only included in the prusa and ratrig configs.

**Comment by miklschmidt** [comment]
Ah, yeah it's global except the prusa-mk3 config overrides the default because the einsy uses 2130's

**Pull request merged**
