### PR TITLE
Update v-core-3-printer.template.cfg

### PR DESCRIPTION
**Pull request by Lordy2001**
Updated lgx-lite extruder direction polarity to match factory wiring.  Also updated comments to prevent confusion.

### CODE REVIEW

**Comment by miklschmidt** [comment]
Just `dir_pin: e_dir_pin # Add ! in front of pin name to reverse extruder direction` is enough.

**Comment by Lordy2001** [comment]
@miklschmidt It is not enough.  I lost 2 hours to reading documentation and it is not at all clear that the default wiring of the bondtech LGX LTE requires reversing the extruder.  Exhibit A: https://www.reddit.com/r/ratrig/comments/13p9xao/bondtech_lgx_lite_issues/

**Comment by miklschmidt** [comment]
@Lordy2001 perhaps i wasn't clear.
Remove this line https://github.com/Rat-OS/RatOS-configuration/pull/133/files#diff-8ae383b26f339f9f17a331a20375622510c1fad17c6e51ae5502f7f901ab40b2R133

And this line https://github.com/Rat-OS/RatOS-configuration/pull/133/files#diff-8ae383b26f339f9f17a331a20375622510c1fad17c6e51ae5502f7f901ab40b2R248

Then remove ! and uncomment this line: https://github.com/Rat-OS/RatOS-configuration/pull/133/files#diff-8ae383b26f339f9f17a331a20375622510c1fad17c6e51ae5502f7f901ab40b2R247

And correct the comment like a described in my previous comment. I'm only accepting this change because the lgx lite + octopus is the current default, all steppers require verifying their directions as it depends on how they're geared, the mounting of the stepper and their wiring, as stated in the docs: https://os.ratrig.com/docs/configuration#verify-stepper-directions

The change you propose actually wouldn't work for somebody who reversed their pins during wiring, or used a board with inverted JST headers such as the SKR Pro 1.2.

Unfortunately it's not as simple as you're trying to make it, but i have another solution for that coming in the future :)

**Comment by miklschmidt** [comment]
I'm closing this, as there seems to be no activity.

**Pull request closed without merging**
