### PR TITLE
Move [mcu] to printer.cfg

### PR DESCRIPTION
**Pull request by aardvarkglory**
Would be very useful to be able to configure the [mcu] from the printer.cfg file instead of the printer config files.

### CODE REVIEW

**Comment by smwoodward** [comment]
You can override the [mcu] section at the bottom of printer.cfg

**Comment by aardvarkglory** [comment]
> You can override the [mcu] section at the bottom of printer.cfg

Yes, but if you use a toolhead, you have to cancel out some things that less advanced people have a hard time with.  Overall, just be easiest to have this variable in the printer.cfg.

**Comment by miklschmidt** [comment]
I don't see the point?

> Yes, but if you use a toolhead, you have to cancel out some things that less advanced people have a hard time with

I don't understand what you mean by this.

**Comment by smwoodward** [comment]
I think what he might be talking about is having the baud in the board config files maybe?  Even with a tool board I didn't need to change much however if someone is using CAN it does require editing the board cfg file because if the baud section. But other than that, it was easy to make the change.

**Comment by miklschmidt** [comment]
@smwoodward 

```
### USER OVERRIDES
[mcu]
baud: 250000
```

There's no point in putting it in the board config files. It does not require editing any files, it's just an override like everything else. Currently all boards use the default klipper baud rate (ie, it's not explicitly configured anywhere).

**Comment by smwoodward** [comment]
If you override the MCU section in printer.cfg to use canbus instead of serial, Klipper gives an error about having the baud rate in the config.

**Comment by miklschmidt** [comment]
@smwoodward what error specifically? You can just add / change the baud rate in the user overrides section like i wrote above, just like anything else. There's no baud rate set in any of the board config files. There's nothing to "unset". Unless you need to unset the serial? In that case, copy paste the board config. CAN is outside the scope of RatOS, i've written plenty about why, there's no compelling advantage to CAN, but lots of compelling advantages to USB.

**Comment by smwoodward** [comment]
image

I'm not arguing of can over USB. That a topic for a different discussion. But if you override this board as can instead of serial, you get an error that baud: in an invalid configuration and the only way to get rid of the error is to make a copy of the board configuration and remove the baud: section.

**Comment by smwoodward** [comment]
I ran into this error when I was setting up canbus and was the only way to get around it.

**Comment by smwoodward** [comment]
Wait I see that he was talking about toolheads. I do wish he would respond with more info he's talking about of what has to be canceled out.

**Comment by miklschmidt** [comment]
@smwoodward ah, that `baud` rate should indeed not be there, that is a bug. 250000 is the default so no reason to list it there.

**Comment by miklschmidt** [comment]
@smwoodward  There were way more than i thought there was, i've removed all of them as they're redundant.

**Comment by aardvarkglory** [comment]
Here is a solution that does not change anything for the average user but at the same time gives the advanced user what he wants. Add config file to each of the board folders and call it config-nomcu.cfg. It would have everything that the normal confic.cfg file has minus the [mcu] lines. All an advanced user would have to do is add (-nomcu) to the printer of choice in the printer.cfg file.

Another way to do this is to make the board mcu a variable (board_mcu=/dev/btt-octopus-pro-429). Then in the printer.cfg file you call it in the [mcu] section. If someone wants to change that, they will have that power and nothing is broken. Just put a note above [mcu] stating any change to this value should not be made.

**Comment by aardvarkglory** [comment]
> Wait I see that he was talking about toolheads. I do wish he would respond with more info he's talking about of what has to be canceled out.

If your board is not interfacing with serial, calling for serial can cause issues if using other methods.  Yes, I am using a toolhead.

**Comment by aardvarkglory** [comment]
Here is a solution that does not change anything for the average user but at the same time gives the advanced user what he wants. Add config file to each of the board folders and call it config-nomcu.cfg. It would have everything that the normal confic.cfg file has minus the [mcu] lines. All an advanced user would have to do is add (-nomcu) to the printer of choice in the printer.cfg file.

Another way to do this is to make the board mcu a variable (board_mcu=/dev/btt-octopus-pro-429). Then in the printer.cfg file you call it in the [mcu] section. If someone wants to change that, they will have that power and nothing is broken. Just put a note above [mcu] stating any change to this value should not be made.

**Comment by miklschmidt** [comment]
Unfortunately there are no variables outside gcode templates and board pin aliases are only for board pins. I can do a variation of the first idea that should work though, will let you know when it’s ready to test.

**Pull request merged**
